name: trashecomate
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  charts_flutter: ^0.11.0
  flutter_spinkit: ^5.2.1
  http: 1.3.0
  firebase_core: ^3.12.1
  firebase_auth: ^5.4.1
  flutter_plugin_android_lifecycle: ^2.0.7
  firebase_database: ^11.3.4
  logger: ^2.5.0
  cloud_firestore: ^5.6.2
  provider: ^6.1.2
  google_maps_flutter: ^2.10.0
  percent_indicator: ^4.2.4
  flutter_local_notifications: ^18.0.1
  firebase_messaging: ^15.2.4
  image_picker: ^1.1.2  
  firebase_storage: ^12.4.2
  mrx_charts: ^0.1.3
  fl_chart: ^0.68.0
  intl: ^0.17.0
  url_launcher: ^6.3.1
  font_awesome_flutter: ^10.1.0
  
  
  # Add any other dependencies your project requires

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.13.1 

flutter:

  uses-material-design: true
  
