// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBghgBHGbK36dZAjfwSI2ykBPxVVhNLO1c',
    appId: '1:584316292909:web:796bee48f1154c30444da4',
    messagingSenderId: '584316292909',
    projectId: 'trashecomate',
    authDomain: 'trashecomate.firebaseapp.com',
    databaseURL: 'https://trashecomate-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'trashecomate.firebasestorage.app',
    measurementId: 'G-Z75VVN27FC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDbEjV8Lq74HZ3_PLCH82pe1DEEn3uaO3A',
    appId: '1:584316292909:android:f8362c7801cf951d444da4',
    messagingSenderId: '584316292909',
    projectId: 'trashecomate',
    databaseURL: 'https://trashecomate-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'trashecomate.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDAxAwLxIxyys3XN7j37NRvXXIMN-GvK9I',
    appId: '1:584316292909:ios:6d1a0a43a4a3aef4444da4',
    messagingSenderId: '584316292909',
    projectId: 'trashecomate',
    databaseURL: 'https://trashecomate-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'trashecomate.firebasestorage.app',
    iosBundleId: 'com.example.trashecomate',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDAxAwLxIxyys3XN7j37NRvXXIMN-GvK9I',
    appId: '1:584316292909:ios:6d1a0a43a4a3aef4444da4',
    messagingSenderId: '584316292909',
    projectId: 'trashecomate',
    databaseURL: 'https://trashecomate-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'trashecomate.firebasestorage.app',
    iosBundleId: 'com.example.trashecomate',
  );
}
